### ISSUE TITLE
Switch auth plugin to JPremium

### ISSUE THREAD

**Issue by angushushu** [CubeX-MC/CubeX#104]
**描述**
之前Akkariin建议换Velocity和LimboAuth。周末本地试了一下，目前迁移和配置都正常。问下啥时候改应用到CubeX合适？(不过需要确认下换LimboAuth效果反机器人效果真的会比AkaneField好么?)

**Comment by AkariDream** [comment]
反机器人实际上为[LimboFilter](https://github.com/Elytrium/LimboFilter)
AkaneField在星悦考虑更换其核心时永远不会考虑替换其它的平台(而且可能会一直使用BungeeCord ~~因为他很懒~~ 因为担心插件兼容性问题)
真正需要担心的是LimboAuth我想保持在线模式启动 所以可以先给几周时间让玩家记录下自己的uuid 离线玩家可以正常进行 在线玩家可以通过联系管理来迁移其背包物品到他们的在线账户上
> *确保所有东西都靠uuid鉴别玩家身份 这样也可以加入floodgate支持.

**Comment by angushushu** [comment]
目前尝试的迁移没有影响在线或离线模式的玩家背包和位置，有空我再试几次。
官方建议的迁移过程不包含uuid，但也许可以直接一起insert过去（另外不知道config里的force-offline-uuid需不需要开启）。

**Comment by AkariDream** [comment]
> 目前尝试的迁移没有影响在线或离线模式的玩家背包和位置，有空我再试几次。 官方建议的迁移过程不包含uuid，但也许可以直接一起insert过去（另外不知道config里的force-offline-uuid需不需要开启）。

因为authme本身就只存储用户名本身

**Comment by AkariDream** [comment]
后端的uuid取决于前端代理 `Velocity` `BungeeCord`

**Comment by angushushu** [comment]
强制离线模式是force-offline-mode，我回头试试开force-offline-uuid有啥效果。暂时还没测试插件的信息存储有没有受影响。

**Comment by AkariDream** [comment]
> 强制离线模式是force-offline-mode，我回头试试开force-offline-uuid有啥效果。

现在应该是 无论如何都应该尝试解决uuid的问题
不能再这样离线下去 这样floodgate都不支持.

> 暂时还没测试插件的信息存储有没有受影响。  

authme不存储uuid信息.

**Comment by AkariDream** [comment]
还有 我觉得全面转uuid是必须的 因为
> Ability to set [UUID](https://minecraft.fandom.com/wiki/Universally_unique_identifier) from [database](https://en.wikipedia.org/wiki/Database);  

但是我想我们可以给玩家一点时间. 就像狼x那样子
即使那些没有时间将那些东西处理好的话 我也有一个用于获取离线uuid的工具.

**Comment by angushushu** [comment]
现在的uuid在哪里可以获取呢？只要能拿到现在的uuid，直接把uuid塞到迁移后的limboauth.db可行么？

**Comment by FallenCrystal** [comment]
> 现在的uuid在哪里可以获取呢？只要能拿到现在的uuid，直接把uuid塞到迁移后的limboauth.db可行么？

这种方式**并不可行**. 那些数据由salt和SHA256存储`SHA256或BCrypt`
再说如果不加密 直接编辑database一不小心也会造成巨大风险和安全隐患.

**Comment by angushushu** [comment]
ok，不行回头用获取离线uuid的工具拿到uuid之后弄个脚本在服务器里一直输limbo的set uuid指令好了

**Comment by FallenCrystal** [comment]
我晚上有时间写个广播自己uuid的玩意吧 让玩家自己储存uuid得了
或者authx在玩家加入时写入跟他们uuid同等的权限.

**Comment by angushushu** [comment]
嗷没有，我是说那个Ability to set UUID from database（但这就需要把拿到的uuid塞到limboauth.db里，离线切换到在线后会继续使用离线）

>   Forcibly set player's UUID to the value from the database
  If the player had the cracked account, and switched to the premium account, the cracked UUID will be used.

回下面那条：好，辛苦了

**Comment by angushushu** [comment]
先换成limboauth然后后期在搞uuid的事情可行不？如果可行在6月前先把登录服撤掉加limboauth？

**Comment by angushushu** [comment]
> 

这段话我不太理解，是想转成正版服？那样相当于放弃离线玩家limboauth也没有使用的必要了不是么？如果这样的话需要权衡一下基岩玩家和离线玩家，目前看离线玩家数量要比基岩玩家多。

**Comment by angushushu** [comment]
> 反机器人实际上为[LimboFilter](https://github.com/Elytrium/LimboFilter) AkaneField在星悦考虑更换其核心时永远不会考虑替换其它的平台(而且可能会一直使用BungeeCord ~因为他很懒~ 因为担心插件兼容性问题)
> 
> > 因为目前(对他来说)没有任何理由迁移到Velocity 我之前跟他讨论过JPremium的性能问题 (~不知道他还记不记得~) 在挨打的时候确实挺糟糕的 LimboAuth要好很多.
> > 针对于最好的反机器人策略仍然是虚拟服务器(认证码其实不太重要 看重力检查吧) AkaneField之后甚至可能会转行不止做反机器人 更像是一个实用工具.
> 
> 真正需要担心的是LimboAuth我想保持在线模式启动 所以可以先给几周时间让玩家记录下自己的uuid 离线玩家可以正常进行 在线玩家可以通过联系管理来迁移其背包物品到他们的在线账户上
> 
> > *确保所有东西都靠uuid鉴别玩家身份 这样也可以加入floodgate支持.

这段话我不太理解，是想转成正版服？那样相当于放弃离线玩家limboauth也没有使用的必要了不是么？如果这样的话需要权衡一下基岩玩家和离线玩家，目前看离线玩家数量要比基岩玩家多。

**Comment by FallenCrystal** [comment]
其实现在来看麻烦大于使用JPremium.
确保所有东西都通过uuid鉴别玩家的意思是 某些插件通过用户名来鉴定玩家身份 这不是很行
未来可能会添加回Geyser支持 但这不是我们的主要任务

**Comment by FallenCrystal** [comment]
如果你想 我可以有一套使用JPremium的计划.

**Comment by angushushu** [comment]
我以为无论怎样离线uuid都是有可能变化的。目前使用用户名的，在离线用户改名后会造成重大影响的插件主要是residence和adapt，两个倒是都可以手动帮忙转移数据，以前也都是这样做的。但是你提到过JPremium不是真正的limbo。
也就是说
- 使用limboauth，性能有优势但插件仍然需要继续用id保存数据
- 使用jpremium，可以实现以uuid保存数据，但会牺牲性能
这二者都比现在的情况要好，但性能和uuid保存需要选择一个。我需要确定jpremium和limboauth在性能上相差多少再做出决定，如果不多那么按照你的jpremium方案是最好的。

**Comment by FallenCrystal** [comment]
我们仍然可以通过外置limbo来完成
最简单的方式是JPremium 因为JPremium从其它地方导入的数据库可以兼容uuid使用. `仅对新账户使用自动生成的方式l`

**Comment by angushushu** [comment]
啊...这两周期末给忘了，这就买

**Comment by AkaneCh4n** [comment]
那你要不然找leak咯

**Comment by AkaneCh4n** [comment]
还有别忘记看看 #112

**Comment by angushushu** [comment]
OK
> 那你要不然找leak咯
没事等spigotmc恢复了我就买

**Comment by AkaneCh4n** [comment]
btw你还需要一个mysql数据库

**Comment by angushushu** [comment]
一个table够么？我有空弄个jpremium table？

**Comment by AkaneCh4n** [comment]
table是自动分配的 你需要一整个db

**Comment by angushushu** [comment]
ok那我新建个jpremium db

**Comment by angushushu** [comment]
已购买，先传到AuthX了，等考完试我看看教程

**Comment by AkaneCh4n** [comment]
> 已购买，先上传disable了，等考完试我看看教程

?用NanoLimbo啊 传AuthX干啥

**Comment by angushushu** [comment]
> > 已购买，先上传disable了，等考完试我看看教程
> 
> ?用NanoLimbo啊 传AuthX干啥

传的时候忘了，回头搞

**Comment by FallenCrystal** [comment]
> > > 已购买，先上传disable了，等考完试我看看教程
> > 
> > 
> > ?用NanoLimbo啊 传AuthX干啥
> 
> 传的时候忘了，回头搞

不及格的api caller和plugin configurationer   xd
你要不先把消息全汉化了 我放假那会来给你弄得了

**Comment by angushushu** [comment]
awa也行，搞还是你靠谱，我后天考完试就开始汉化

**Comment by AkaneCh4n** [comment]
你插件丢哪去了

**Comment by angushushu** [comment]
好像放data下面Limbo文件夹里了，虽然应该放BC和所有paper端下面

**Comment by FallenCrystal** [comment]
你说得对 但我没找到
而且没必要放每个服务器实例下面

**Comment by angushushu** [comment]
寄，可能我没传上去？我一会到家再传一下

**Comment by angushushu** [comment]
看了下就在limbo目录下，你是不是没找到data，data就是默认路径，limbo和survival啥的都在data下面

**Comment by FallenCrystal** [comment]
> 你说得对 但我没找到 而且没必要放每个服务器实例下面

.
u should only put it on bungeecord.

**Comment by angushushu** [comment]
放到BC了，我还没翻译完，尽量这两天弄完

**Comment by FallenCrystal** [comment]
> 放到BC了，我还没翻译完，尽量这两天弄完 提醒下limbo没配置好好像jpremium会强制关闭bc 翻译完了，传bc了

你db都没配置开毛线 乐了

**Comment by FallenCrystal** [comment]
ok we need to announce to maintenance i think

**Comment by FallenCrystal** [comment]
oops我搞砸了一些东西 现在.. 先把白名单开起来再说吧

**Comment by FallenCrystal** [comment]
done

**Comment by angushushu** [comment]
啊刚起...这么快，我以为后面还得要几天。thx

**Comment by FallenCrystal** [comment]
可以 AuthX是我转换数据库时开着的

**Comment by angushushu** [comment]
不怀疑awa，那个令牌验证的二维码我刚试了一下，但是手机扫描二维码出不来令牌文本。我先把注册提示里的"<令牌>"改成"<令牌<-可不填>"

**Comment by FallenCrystal** [comment]
你还可不填可不填的

**Comment by FallenCrystal** [comment]
后端压根就不是spigot服务器

**Comment by FallenCrystal** [comment]
jpremium难不成还有超能力在代理上设置物品

> 虽然我有

**Comment by angushushu** [comment]
就那个二维码的网页能打开，不知道是不是我手机问题扫不出令牌。那干脆我把提示里的"<令牌>"删了

**Comment by FallenCrystal** [comment]
> 就那个二维码的网页能打开，不知道是不是我手机问题扫不出令牌。那干脆我把提示里的"<令牌>"删了

你别管那破2FA了JPremium的2FA就是个几把

**Comment by FallenCrystal** [comment]
而且验证码和2FA压根就不是一个东西你别搞混淆了谢谢

**Comment by angushushu** [comment]
OK，我就把那个提示关了以防老有新人问
