### ISSUE TITLE
是否将此储存库重命名然后迁移到CatMoe组织?

### ISSUE THREAD

**Issue by FallenCrystal** [CubeX-MC/CubeX#110]
~~我不想再在这个账户留下什么储存库了~~

**Comment by FallenCrystal** [comment]
错别字oops

**Comment by angushushu** [comment]
要不要弄个CubeX组织，顺便把网页也放进去。看你

**Comment by FallenCrystal** [comment]
我懒得弄说实话

**Comment by FallenCrystal** [comment]
你现在应该已经是外部合作者 且是该储存库的管理员.  

> btw 邀请是无效的

**Comment by FallenCrystal** [comment]
> huh奇怪，那个cubex的网页能迁到catmoem么...不过会占个page

wdym

**Comment by angushushu** [comment]
> > huh奇怪，那个cubex的网页能迁到catmoem么...不过会占个page
> 
> wdym

就是会占个静态托管的位置，或者我放到CubeX-MC也行

**Comment by AkaneCh3n** [comment]
已经迁移了

> 改个logo吧

**Comment by angushushu** [comment]
> 改个logo吧
org的吗，ok
