### ISSUE TITLE
[update] 升级1.19.4

### ISSUE THREAD

**Issue by angushushu** [CubeX-MC/CubeX#111]
**描述**
升级到版本1.19.4？还是等1.20，会不会有点遥远

**任务清单**
- [x] 检查插件xxx（已上传
- [x] 本地测试 （跑了一小下没问题

**补充**
1.19.3已改为paper

**Comment by FallenCrystal** [comment]
不推荐现在升级1.19.4
待我认为需要升级时 我会重新打开此问题.

**Comment by FallenCrystal** [comment]
可以有空看看 但其实仍然不建议 ——有太多的东西未修复
而且此次更新我并不考虑打算使用任何其它fork ——也就是原Paper

**Comment by angushushu** [comment]
ok，那我本地也先用paper试一下

**Comment by FallenCrystal** [comment]
你试毛线

**Comment by angushushu** [comment]
嗷那我不试

**Comment by FallenCrystal** [comment]
Create a new issue on update 1.20
