### ISSUE TITLE
是否上nullcordx

### ISSUE THREAD

**Issue by AkaneCh4n** [CubeX-MC/CubeX#112]
[Polymart Link](https://polymart.org/resource/nullcordx-30-off.1476)

白嫖到一个免费许可证 你想试试的话可以玩玩

> 但是先说好了 你别给我许可证泄露了要不然我打死你

> 如果你换ip或者换硬件了记得告诉我 要不然我给你头都打下来

**Comment by angushushu** [comment]
喔，ok thx，回头有空在vps上试试

**Comment by AkaneCh4n** [comment]
许可证发群里了

**Comment by angushushu** [comment]
已更换为nullcordx，不过看起来国际线路的动态ip重复掉落验证有点要命

**Comment by FallenCrystal** [comment]
你说得对 你可以调玩家直接加入服务器

**Comment by FallenCrystal** [comment]
> 还寄吧顾着你那破国际线路呢

**Comment by angushushu** [comment]
> > 还寄吧顾着你那破国际线路呢

主要想省加速器的钱
