### ISSUE TITLE
#113 回答问题的副本

### ISSUE THREAD

**Issue by AkaneCh4n** [CubeX-MC/CubeX#115]
@angushushu 
1. 玩家被断开连接 `Internal Exception .... Connection reset` 然后被列入黑名单这一行为?
很显然 这其实是故意的

当真正遇到像Connection reset此类行为的时候 玩家实际上并没有根据TCP断开连接的正确顺序切断他们的连接 并且应该由WaterFall抛出Exception 而不是在PostLogin时只是提示一行他们被踢出的理由 如果我需要再高级一点 我甚至可以模仿Exception 但我的真正目的是恶心那些人 而不是伪装成合法的像病毒一样的软件在你们的计算机里

[BulletProofShitDetector.kt L1-36](https://github.com/CatMoe/AkaneField/blob/main/src/main/java/catmoe/fallencrystal/akanefield/expansion/domain/BulletProofShitDetector.kt#L1-L36)   和   [MainListener.kt L144-158](https://github.com/CatMoe/AkaneField/blob/main/src/main/java/catmoe/fallencrystal/akanefield/listener/MainEventListener.kt#L144-L158) 说明了一切

我这么做的原因 你应该也知道 为什么我不将我不喜欢的所有人列进去 这是有理由的 至于是为什么 这些人接触过哪些人 你自己思考一下吧 你或许也可以通过人脉来知道这一点 或许已经有人告诉你了.

关闭的方法也很简单:
[ConfigManager.java L203](https://github.com/CatMoe/AkaneField/blob/main/src/main/java/catmoe/fallencrystal/akanefield/common/utils/ConfigManager.java#L203)
你只需要在配置文件的顶部新增一行. `i-want-to-disable-shit-check: true` 即可关闭该检查

你可能会问我我为什么要这么做 很显然我可以偷偷摸摸在你们的Release包里干这事 并且不告诉你们关闭的方法. 我知道这会影响我的声誉或者其它一些东西 我敢放在Github上是有理由的. 我对我的代码拥有绝对权力. 我本来一开始只是在想给指定一个服务器制作这个 让它看起来像合法的一样 但不是 我最后思考了一会 最终决定面向全部人 当他们遇到这个问题时 我再把解决方法告诉他们.

2. Bot文件夹是干什么用的
很显然 是压力测试用的 但那个文件夹实际上已经被废弃了 并且其实没什么用 因为我目前不需要.

3. 我最近这段时间干什么去了
我在忙着一些CatMoe的**私有项目** 如果你想你也可以认为我故意不理你 但我这么最终回复你是有理由的 我倒不至于坏到这点东西都不告诉你.

**Comment by AkaneCh4n** [comment]
如果你真的不想让其它人知道这些 你也可以直接告诉我删除这个issue 但可能保持透明是更好的选择

> 你想不想看到08被黑名单的时候大家开香槟的样子? 哈哈^ ^

**Comment by angushushu** [comment]
没必要把这个说出来，我觉得这玩意你现在弄了倒没什么但放以后对你也算不太好的历史了。就删掉吧，反正都改回去了，就当没发生。只是我仍然觉得，个人的喜好和公共事物还是应该分开，之前也跟你说过，当然听不听就是你的事了。这个issue删了吧，以后别人看见对你也不好。

**Comment by AkaneCh4n** [comment]
放出来就放出来咯

> 你想不想看到08被黑名单的时候大家开香槟的样子? 哈哈^ ^
> > 看来你是真没看过呢

很早就有人注意过这个了 其实挺多人知道这个代码的.
我之后甚至还会不给任何的方式绕过这个

> 那bot文件夹我删了？

随便

> 个人的喜好和公共事物还是应该分开

但我不认为傻逼说的上是公共事物 我说这些只是**回答 仅此而已 我没有义务透露太多 以及哪些人知道这些事**

**Comment by AkaneCh4n** [comment]
你自己鉴别一下是什么成分
![image](https://user-images.githubusercontent.com/129195594/236635356-8d09144e-31da-4ecb-8b8e-12a6486ce528.png)

**Comment by AkaneCh4n** [comment]
![)TTV 22{SA58~U@C M)ET](https://user-images.githubusercontent.com/129195594/236635433-ef2ad834-21fd-479e-94a0-24707755688e.png)

**Comment by AkaneCh4n** [comment]
聊天记录里面还有马克q开纪被ban来找我求情的 一个个都小丑的 倒也是 给他们点自尊心 不全都放出来 ^ ^

**Comment by AkaneCh4n** [comment]
还有滥用职权的事情一把一把的呢 之前处理了一些 后面还有一些是找夏洛特整的

**Comment by AkaneCh4n** [comment]
你怎么处置是你的事情

**Comment by AkaneCh4n** [comment]
对了我这里还有08开纪狡辩喊爸爸的珍贵影像你要不要看看 ^^

**Comment by AkaneCh4n** [comment]
这事就这样过去了 之后我想咋整还是咋整 反正背后发生了挺多不知道的东西的 你想看看的话随时叫我都行

**Comment by angushushu** [comment]
如果处罚就光明正大地处罚，没必要以这种方式。我说是公共事务是因为涉及到服务器管理，这肯定是要大家一起讨论的，如果不讨论就要严格按照规则走。我还是觉得你该把这个issue删掉，你现在无所谓声誉，以后呢？

**Comment by AkaneCh4n** [comment]
让你好好看看你那群管理和玩家都是啥贵物 混下来就夏洛特一个好的

**Comment by AkaneCh4n** [comment]
> 你现在无所谓声誉，以后呢？
我无所谓啊

**Comment by AkaneCh4n** [comment]
> 如果处罚就光明正大地处罚，没必要以这种方式。我说是公共事务是因为涉及到服务器管理，这肯定是要大家一起讨论的

公共事物死在圣母上 大家一起讨论你看什么时候宽容过那群傻逼了

**Comment by angushushu** [comment]
这跟圣母没关系吧，我不反对处罚，但是不认为应该搞偷偷摸摸的东西。至于你说的服务器管理的问题，我最近没看到什么问题，不过也许管理员是该刷一下了（反正三个管理最近也不怎么上线）。
别的没啥了，你要是不想删这issue就留着吧，反正以后随时也可以删。

**Comment by AkaneCh4n** [comment]
关于那些神权物品那些事 我只是听说你好像全部让夏洛特负责是吧 我不觉得你有太多的眼睛可以站在多方面角度评价这些事
但你是不是忘记了他们没有处罚的权利?

**Comment by AkaneCh4n** [comment]
我相信你理解下上面的话你就知道为什么08会回来 是谁拉他会来的

你不在的时候08可没少阴阳过我和星悦呢 难不成你的眼睛只有停在我提醒星悦那天是他生日发的空间的留言上?

**Comment by angushushu** [comment]
我知道阴阳他人不是什么好事情，毕竟阴阳我的人也不少。但这毕竟算是私人矛盾，我觉得不该转移到服务器处罚里。他们的问题按照规则处罚就好了。另外毕竟你说的他们的很多问题都是在咱们修改规则之前了，之后也没有发生过什么新的问题吧。既然如此我觉得应该盯着现在发生的而不是已经有定论的事情。

**Comment by AkaneCh4n** [comment]
> 另外毕竟你说的他们的很多问题都是在咱们修改规则之前了

?所以之前的事情完全就是一笔勾销了是吗?

> 但这毕竟算是私人矛盾

私人矛盾跟傻逼惹事还是有区别的

**Comment by AkaneCh4n** [comment]
> 我觉得应该盯着现在发生的而不是已经有定论的事情。

现在的事情是 马克q进不来服 自然也就暂时没了滥用职权这一说 但08还在

还有些隐藏傻逼 例如pigpig711 当然他确实干的事情还影响没特别严重 比起滥用职权什么的傻逼来说 我暂时就先不计较 当然规则肯定还是打破过的

**Comment by AkaneCh4n** [comment]
再说了 投票现在完全没有公信力 因为马克q那里有甜头 不出所料马克q还是能当管理

**Comment by angushushu** [comment]
> > 另外毕竟你说的他们的很多问题都是在咱们修改规则之前了
> 
> ?所以之前的事情完全就是一笔勾销了是吗?
一笔勾销不是因为规则修改了，是因为之前已经处罚过了。Mark撤职了（我知道他后来又当上了，是我改规则不及时），08我感觉他现在只是嘴欠点。pigpig感觉还好吧。



> 再说了 投票现在完全没有公信力 因为马克q那里有甜头 不出所料马克q还是能当管理

有问题，但有没有公信力不知道因为倒是没玩家骂过这个机制。夏洛特每次票数都最低，所以我现在想撤别人又保他就做不太到

**Comment by angushushu** [comment]
不知道，我真不想看cbx变成那种服主管理把一些人ban掉然后让服务器气氛往某个人的喜好发展的样子。我是希望保持一种相对开放的状态，所以才那么希望尊重规则。也许我们可以把管理统一清理掉，以后用提拔的制度。但这样做感觉有种任人唯亲的感觉。

**Comment by AkaneCh4n** [comment]
> 一笔勾销不是因为规则修改了，是因为之前已经处罚过了。Mark撤职了（我知道他后来又当上了，是我改规则不及时），08我感觉他现在只是嘴欠点。pigpig感觉还好吧。

? 那就是你所谓的处罚吗?

> 08我感觉他现在只是嘴欠点

人的本性是难改的 他真正成熟还得随着时间推移 那也是三四年之后的事情了

> pigpig感觉还好吧。

是 相对于其他人来讲


> 有问题，但有没有公信力不知道因为倒是没玩家骂过这个机制。夏洛特每次票数都最低，所以我现在想撤别人又保他就做不太到

玩家不骂这个机制我虽然不能说是完全因为马克q 但马克q人缘还算广的 他要是真想搞大事情很容易

**Comment by AkaneCh4n** [comment]
> 不知道，我真不想看cbx变成那种服主管理把一些人ban掉然后让服务器气氛往某个人的喜好发展的样子。我是希望保持一种相对开放的状态，所以才那么希望尊重规则。也许我们可以把管理统一清理掉，以后用提拔的制度。但这样做感觉有种任人唯亲的感觉。


> 我真不想看cbx变成那种服主管理把一些人ban掉然后让服务器气氛往某个人的喜好发展的样子

这么做并不指定某个人的喜好 但xmzh那样是一个很鲜明的错误例子

> 我是希望保持一种相对开放的状态

局势已经很明了了 要不管 要不完全无政府 这样下去不是废就是半残

> 也许我们可以把管理统一清理掉，以后用提拔的制度

现在根本没多少老玩家想管服 新玩家想当大概率是啥也不当或者来捣乱的 但你要是说只是推荐制的话 那应该还算好 但起码保底被撤职了之后不能再当 我不相信会有因为权限而被**完全撤职**的情况 至少现在不会有

**Comment by AkaneCh4n** [comment]
说东西啥的 别老总是避开麻烦 反正 lock conversation是个好东西

**Comment by angushushu** [comment]
管肯定是要管，毕竟养老服。我的建议是先从管理下手。08的问题我不太确定，因为如果他只是对于管理傻逼，处理他对其他玩家来说看起来非常不合理。
5月不弄管理投票了，我中间改下规则。6月全部刷掉然后把夏洛特提上来。

**Comment by AkaneCh4n** [comment]
> 因为如果他只是对于管理傻逼

你可以去问问yzh 他应该挺深有感触的

**Comment by angushushu** [comment]
> > 因为如果他只是对于管理***
> 
> 你可以去问问yzh 他应该挺深有感触的

ok我先走访一下

**Comment by angushushu** [comment]
> 5月不弄管理投票了，我中间改下规则。6月全部刷掉然后把夏洛特提上来。

刚想起来不用，现在规则支持服主和op投票罢免管理。我直接在群里发个罢免Mark和Zhongling的投票，你让星悦拉你进微信群投票。

**Comment by AkaneCh4n** [comment]
> 你让星悦拉你进微信群投票。

他已经睡了.

**Comment by angushushu** [comment]
> > 你让星悦拉你进微信群投票。
> 
> 他已经睡了.

不急，过几天在弄也行。你进群我再发。你也早睡
