### ISSUE TITLE
[update] 降低max-chained-neighbor-updates

### ISSUE THREAD

**Issue by angushushu** [CubeX-MC/CubeX#117]
**描述**
玩家用update skipper做切门要超过max-chained-neighbor-updates，原值为1000000。降低到10000防止过多的更新也许能够避免大量玩家被踢的问题？打算先降到10000试几天。

**补充**
还是说建议直接禁用update skipper，改为负值？

**Comment by AkaneCh4n** [comment]
why allow it. unless ure willing to execute an infinite of "try catch" statements on the main thread on ur server to catch the StackOverflowException and kill ur CPU usage and G1GC.

**Comment by angushushu** [comment]
K, will turn it to a neg Val. Just one question: wouldn't disabling the skipper leads to a lack of protection for too many chained updates?

**Comment by AkaneCh4n** [comment]
> wouldn't disabling the skipper lead to a lack of protection for too many chained updates?

recommend a maximum of 128

> Which can affect the tps heavily I guess?

when throwed StackOverflowException. i dont think anyone would write code relying on exception. unless they actually do something that violates the expected behavior.

**Comment by angushushu** [comment]
Done, I was thinking some redstone machine might need a large number of chained updates, but seems it not to be the case

**Comment by AkaneCh4n** [comment]
> Done, I was thinking some redstone machines might need a large number of chained updates, but seems that is not the case

i dont think there is any redstone toy can trigger 128 chain block updates within **1tick**.
