### ISSUE TITLE
[update] Update on 1.20

### ISSUE THREAD

**Issue by FallenCrystal** [CubeX-MC/CubeX#119]
**描述**
.

**任务清单**
.

**补充**
.

**Comment by FallenCrystal** [comment]
matrix处于激活码限制为完全测试

> 你不是买了吗

**Comment by angushushu** [comment]
我承认也有一部分懒惰的因素在里面

**Comment by angushushu** [comment]
大约7月13-15号左右升级如何？
可能要停服几天下载下届和末地然后用MCASelector清理一下。

**Comment by FallenCrystal** [comment]
> 大约7月13-15号左右升级如何？ 可能要停服几天下载下届和末地然后用MCASelector清理一下。

我目前没有多余的精力来处理这些  你自己的话那就没啥问题

**Comment by angushushu** [comment]
> > 大约7月13-15号左右升级如何？ 可能要停服几天下载下届和末地然后用MCASelector清理一下。
> 
> 我目前没有多余的精力来处理这些 你自己的话那就没啥问题

应该问题不大，你没有要检查的东西就行

**Comment by angushushu** [comment]
更新：
基本上更新完了？剩下一些小问题后面就慢慢解决了
1. advancedban貌似因为迁移到新机器没有数据库授权，暂时把advancedban disable了
2. adapt有些技能据说失效了，回头我删除一下配置重新加载一遍
3. 看看15m带宽够不够，不够我去申请用捐款加一下
4. 新机器在枣庄，具体信息在后台网站能看到

**Comment by FallenCrystal** [comment]
> advancedban貌似因为迁移到新机器没有数据库授权，暂时把advancedban disable了

这用的是我的db

> adapt有些技能据说失效了，回头我删除一下配置重新加载一遍

不要取消禁用 ——直到我认为那些技能不会造成影响为止

**Comment by angushushu** [comment]
> > advancedban貌似因为迁移到新机器没有数据库授权，暂时把advancedban disable了
> 
> 这用的是我的db
> 
> > adapt有些技能据说失效了，回头我删除一下配置重新加载一遍
> 
> 不要取消禁用 ——直到我认为那些技能不会造成影响为止

嗯，在挨个改

**Comment by angushushu** [comment]
然后海外线路关掉了
