### ISSUE TITLE
使用MoeFilter

### ISSUE THREAD

**Issue by FallenCrystal** [CubeX-MC/CubeX#120]
MoeFilter经过了 https://github.com/CatMoe/MoeFilter/issues/23 的修改之后已经兼容JPremium. 并且现在运行在~3个服务器上没有任何问题 `Test API v8`
目前MoeFilter不支持NullCordX. 也并非一定要卸载MoeFilter. 目前MoeFilter提供两种模式:

### Pipeline
让MoeFilter抢劫BungeeCord的管道并**完全接管**BungeeCord的网络
事实上 经过测试 
MoeFilter比NullCordX快得多. 我承诺我会在下周内完成所有基本反机器人检查 `First-Join` `Ping-Join` `etc..` (已完成)

### Event
优雅地获取管道并接管管道 也可以提供相当高的性能 但是不如Pipeline模式 此模式与NullCordX兼容.

### Disable
啥也不干 当实用工具使用

选择哪个取决于你 但请注意 MoeFilter作为一个付费开源插件 ~(10$) 如果你想补差价 可以待v1 release时找我. 即使你不补 我当然也会让你用.

**Comment by xism4** [comment]
> MoeFilter经过了 [CatMoe/MoeFilter#23](https://github.com/CatMoe/MoeFilter/issues/23) 的修改之后已经兼容JPremium. 并且现在运行在~3个服务器上没有任何问题 `Test API v8` 目前MoeFilter不支持NullCordX. 也并非一定要卸载MoeFilter. 目前MoeFilter提供两种模式:
> 
> ### Pipeline
> 让MoeFilter抢劫BungeeCord的管道并**完全接管**BungeeCord的网络 事实上 经过测试 MoeFilter比NullCordX快得多. 我承诺我会在下周内完成所有基本反机器人检查 `First-Join` `Ping-Join` `etc..` (已完成)
> 
> ### Event
> 优雅地获取管道并接管管道 也可以提供相当高的性能 但是不如Pipeline模式 此模式与NullCordX兼容.
> 
> ### Disable
> 啥也不干 当实用工具使用
> 
> 选择哪个取决于你 但请注意 MoeFilter作为一个付费开源插件 ~(10$) 如果你想补差价 可以待v1 release时找我. 即使你不补 我当然也会让你用.

Is not faster than nullcordx, since it works with events handled by the proxy.
